const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const sharp=require('sharp');const c=require('../lib/photo-critiques/core.cjs');
process.env.CRITIQUE_ADMIN_SECRET='test-only-secret-not-used-in-production-123456789';
const valid=()=>({submissionId:crypto.randomUUID(),name:'Test photographer',email:'test@example.com',instagram:'@photographer',rights:true,permission:true,editing:true,consentVersion:c.CONSENT,images:[{}]});
test('requires permissions, identity, and one to three photographs',()=>{for(const patch of [{rights:false},{permission:false},{instagram:''},{email:'bad'},{images:[]},{images:[{},{},{},{}]},{company:'bot'}])assert.throws(()=>c.validate({...valid(),...patch}),c.PublicError);assert.equal(c.validate(valid()).status,'New');});
test('rejects executable or credential-bearing website URLs',()=>{for(const website of ['javascript:alert(1)','https://user:password@example.com','file:///etc/passwd'])assert.throws(()=>c.validate({...valid(),website}),c.PublicError);assert.equal(c.validate({...valid(),website:'example.com'}).website,'https://example.com/');});
test('malformed images fail and valid images are decoded, limited, and metadata-stripped',async()=>{await assert.rejects(()=>c.imageBytes({data:'data:image/jpeg;base64,aGVsbG8='}),c.PublicError);const input=await sharp({create:{width:2600,height:100,channels:3,background:'#cc8833'}}).jpeg().withMetadata().toBuffer();const output=await c.imageBytes({data:'data:image/jpeg;base64,'+input.toString('base64')});const meta=await sharp(output).metadata();assert.equal(meta.width,2400);assert.equal(meta.format,'jpeg');assert.equal(meta.exif,undefined);});
test('private session rejects missing, tampered, expired and malformed cookies',()=>{assert.equal(c.isAdmin({headers:{}}),false);const good=c.session();assert.equal(c.isAdmin({headers:{cookie:'critique_session='+good}}),true);assert.equal(c.isAdmin({headers:{cookie:'critique_session='+good+'x'}}),false);assert.equal(c.isAdmin({headers:{cookie:'critique_session=1.'+c.mac('session:1')}}),false);assert.equal(c.equal('a','é'),false);});
test('private storage marks all writes private and reads uncached',async()=>{const calls=[];const store=c.createStore({put:async(...a)=>calls.push(a),get:async(...a)=>{calls.push(a);return null;}});await store.write('records/example.json',{name:'test'});await store.image('images/example/0.jpg',Buffer.from('test'));await store.read('records/example.json');assert.equal(calls[0][2].access,'private');assert.equal(calls[1][2].access,'private');assert.equal(calls[2][1].useCache,false);});

test('requires current consent and separate editing approval; saves the wording shown',()=>{
 for(const patch of [{editing:false},{editing:undefined},{consentVersion:undefined},{consentVersion:'2026-09-25-v1'}])assert.throws(()=>c.validate({...valid(),...patch}),c.PublicError);
 const record=c.validate(valid());assert.equal(record.consent.editing,c.EDITING);assert.deepEqual(record.consent.acknowledgements,{rights:true,permission:true,editing:true});assert.ok(Date.parse(record.consent.acceptedAt));
 const html=require('node:fs').readFileSync(require('node:path').join(__dirname,'../image-critique/index.html'),'utf8');
 assert.ok(html.includes('data-consent-version="'+c.CONSENT+'"'));
 for(const [id,wording]of [['rights',c.RIGHTS],['permission',c.PERMISSION],['editing',c.EDITING]])assert.ok(html.includes('id="'+id+'" required><span>'+wording+'</span>'));
});
